import base64

from learn.thought.ithought import IThought


@IThought.thought_type("audio/mpeg")
class AudioThought(IThought):
    """
    Encapsulates base64 audio data along with related metadata.
    Generated by audio-based LLM calls like text-to-speech and returned to callers.
    Allows Node AI components to transport and store synthesized speech.
    """

    def __init__(self, content: str, role: str = "assistant", **kwargs):
        """
        :param content: Base64-encoded audio data.
        :param role: Usually 'assistant' (after TTS generation).
        :param kwargs: Additional metadata (e.g., 'query', 'voice', 'speed', etc.).
        """
        super().__init__(content=content, role=role, **kwargs)

    @property
    def query(self) -> str:
        """
        The text prompt or user request that generated this audio, if any.
        """
        return self.get("query", "")